apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-p1ty
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-p1ty@sha256:f52e13aa4a883f51553e9c7e1d0bd331f2053827eb1b5466d4014ff691f95077
        name: my-nodejs
        resources: {}
status: {}
